python run_full.py gridworld > log_gridworld.txt &
python run_full.py ntu > log_ntu.txt &
python run_full.py pursuit-task > log_pursuit_task.txt &
python run_full.py pursuit-teammate > log_pursuit_teammate.txt &
python run_full.py pursuit-both > log_pursuit_both.txt &
python run_full.py overcooked > log_overcooked.txt &
python run_full.py isr > log_isr.txt &
python run_full.py mit > log_mit.txt &
python run_full.py pentagon > log_pentagon.txt &
python run_full.py cit > log_cit.txt &
